### PR TITLE
Blueprints fragment requirements

### PR DESCRIPTION
**Pull request by stephenengland**
This will change the number of fragments required in order to add a blueprint. So if you do this to the config:

```
{
	"DayNightCycleMultiplier": 1.0,
	"CraftingCostMultiplier": 1,
	"PowerUsedPerCraft": 15.0,
	"CyclopsShieldPowerCost": 50.0,
	"CyclopsSonarPowerCost": 10.0,
	"CyclopsSilentPowerCost": 5.0,
	"PlantGrowRateMultiplier": 1.0,
	"MaproomPowerDrainMultiplier": 0.5,
	"HealthRegenerationThreshold": 0.75,
	"HealthRegenerationAmount": 0.5,
	"HealthKitRestoreAmount": 50.0,
	"BladderFishOxygenValue": 15.0,
	"RawDamageMultiplier": 1.0,
	"HealthMax": 100.0,
	"FoodMax": 100.0,
	"WaterMax": 100.0,
	"FoodOverchargeMax": 150.0,
	"HealthRespawnRatio": 0.6,
	"FoodStart": 60.0,
	"WaterStart": 40.0,
	"FoodDrainMultiplier": 1.0,
	"WaterDrainMultiplier": 1.0,
	"OxygenDrainMultiplier": 1.0,
	"PrawnSeamothPowerDrainMultiplier": 1.0,
	"HandToolsPowerDrainMultiplier": 1.0,
	"StarvationDamageMultiplier": 25.0,
	"DehydrationDamageMultiplier": 25.0,
	"Blueprints": {
		"Seamoth": 5,
		"Seaglide": 5
	}
}

```

You will need 5 Seamoth fragments to earn the Seamoth Blueprint and 5 to earn the glider.

I've come up with suggested values for people if they want a more difficult playthrough.

I've also added the example config, based on your packaged release's config and my added changes.

### CODE REVIEW

**Comment by ghost** [comment]
Seems great! Good idea too!

**Comment by Alexejhero** [comment]
Nice touch

**Comment by stephenengland** [comment]
Alright I've gone through two playthroughs:

- one where I bumped each fragment up by one and assessed what the values should be for a "harder" game
- one where I used the suggested.json values.

I'm pretty happy with how difficult it makes the game! If you do not want this in your mod, I'll be making a new one, so some feedback would be appreciated.

**Comment by ghost** [comment]
I think you should definately make this a seperate mod. Because many users would probably only want the feature you made, and not all the others in snhardcoreplus.. Its your call. But thats what i think! Anyway your thingie works great! I tested it and i am loving the extended difficulty of more fragments!

**Comment by stephenengland** [comment]
It looks like this won't be getting added to SNHardcorePlus. I made a repo with what I'm currently working on: https://github.com/thealah/SubnauticaRandomizer

It will include this feature. It will also include a recipe randomization feature that I'm working on that is inspired by http://vt.alttp.run/, a randomizer that makes one of my favorite games more re-playable!

**Pull request closed without merging**
